name: Deploy Website

on:
  push:
    branches:
      - main   # or master, depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # No build step needed since it’s plain HTML/CSS/JS
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # root of the repo (where index.html is)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
